/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nutricorp.visuales;

/**
 *
 * @author gg
 */
public class CrearDieta extends javax.swing.JInternalFrame {

    /**
     * Creates new form CrearDieta
     */
    public CrearDieta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoDietas2 = new javax.swing.JDesktopPane();
        TXTND = new javax.swing.JLabel();
        CBCliente = new javax.swing.JComboBox<>();
        TXTCliente = new javax.swing.JLabel();
        TFNombreDieta = new javax.swing.JTextField();
        TXTFechaInicio = new javax.swing.JLabel();
        TXTFechaInicial = new javax.swing.JLabel();
        DateChooserFechaInicio = new com.toedter.calendar.JDateChooser();
        TXTPesoInicio = new javax.swing.JLabel();
        TXTPesoFinal = new javax.swing.JLabel();
        DateChooserFechaFinal = new com.toedter.calendar.JDateChooser();
        TFPesoInicial = new javax.swing.JTextField();
        TFPesoFinal = new javax.swing.JTextField();
        ButtonEliminar = new javax.swing.JButton();
        ButtonEditar = new javax.swing.JButton();
        ButtonGuardar = new javax.swing.JButton();
        ButtonBuscar = new javax.swing.JButton();
        TXTSeleccionarDieta = new javax.swing.JLabel();
        barritasAguanteBoca = new javax.swing.JLabel();
        CBSeleccionarDieta = new javax.swing.JComboBox<>();

        setClosable(true);
        setTitle("Crear/Editar Dietas");

        FondoDietas2.setBackground(new java.awt.Color(204, 204, 204));

        TXTND.setText("Nombre de la Dieta:");

        TXTCliente.setText("Cliente:");

        TXTFechaInicio.setText("Fecha Inicio:");

        TXTFechaInicial.setText("Fecha Final:");

        TXTPesoInicio.setText("Peso Inicial:");

        TXTPesoFinal.setText("Peso Final:");

        ButtonEliminar.setText("Eliminar");

        ButtonEditar.setText("Editar");

        ButtonGuardar.setText("Guardar");

        ButtonBuscar.setText("Buscar");

        TXTSeleccionarDieta.setText("Seleccionar Dieta");

        barritasAguanteBoca.setBackground(new java.awt.Color(0, 0, 0));
        barritasAguanteBoca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        barritasAguanteBoca.setText("________________________________________________");

        FondoDietas2.setLayer(TXTND, javax.swing.JLayeredPane.DEFAULT_LAYER);
        FondoDietas2.setLayer(CBCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        FondoDietas2.setLayer(TXTCliente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        FondoDietas2.setLayer(TFNombreDieta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        FondoDietas2.setLayer(TXTFechaInicio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        FondoDietas2.setLayer(TXTFechaInicial, javax.swing.JLayeredPane.DEFAULT_LAYER);
        FondoDietas2.setLayer(DateChooserFechaInicio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        FondoDietas2.setLayer(TXTPesoInicio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        FondoDietas2.setLayer(TXTPesoFinal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        FondoDietas2.setLayer(DateChooserFechaFinal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        FondoDietas2.setLayer(TFPesoInicial, javax.swing.JLayeredPane.DEFAULT_LAYER);
        FondoDietas2.setLayer(TFPesoFinal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        FondoDietas2.setLayer(ButtonEliminar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        FondoDietas2.setLayer(ButtonEditar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        FondoDietas2.setLayer(ButtonGuardar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        FondoDietas2.setLayer(ButtonBuscar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        FondoDietas2.setLayer(TXTSeleccionarDieta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        FondoDietas2.setLayer(barritasAguanteBoca, javax.swing.JLayeredPane.DEFAULT_LAYER);
        FondoDietas2.setLayer(CBSeleccionarDieta, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout FondoDietas2Layout = new javax.swing.GroupLayout(FondoDietas2);
        FondoDietas2.setLayout(FondoDietas2Layout);
        FondoDietas2Layout.setHorizontalGroup(
            FondoDietas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoDietas2Layout.createSequentialGroup()
                .addGroup(FondoDietas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(FondoDietas2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(FondoDietas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ButtonEliminar)
                            .addComponent(TXTFechaInicio)
                            .addComponent(TXTPesoFinal)
                            .addComponent(TXTND)
                            .addComponent(TXTCliente)
                            .addGroup(FondoDietas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TXTPesoInicio)
                                .addComponent(TXTFechaInicial)))
                        .addGroup(FondoDietas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FondoDietas2Layout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addComponent(ButtonEditar)
                                .addGap(30, 30, 30)
                                .addComponent(ButtonGuardar))
                            .addGroup(FondoDietas2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(FondoDietas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CBCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TFNombreDieta, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DateChooserFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DateChooserFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(FondoDietas2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(FondoDietas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TFPesoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TFPesoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, FondoDietas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoDietas2Layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TXTSeleccionarDieta)
                            .addGap(18, 18, 18)
                            .addComponent(CBSeleccionarDieta, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(42, 42, 42)
                            .addComponent(ButtonBuscar))
                        .addGroup(FondoDietas2Layout.createSequentialGroup()
                            .addGap(74, 74, 74)
                            .addComponent(barritasAguanteBoca, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        FondoDietas2Layout.setVerticalGroup(
            FondoDietas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoDietas2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(FondoDietas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonBuscar)
                    .addComponent(TXTSeleccionarDieta)
                    .addComponent(CBSeleccionarDieta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(barritasAguanteBoca)
                .addGap(31, 31, 31)
                .addGroup(FondoDietas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTND)
                    .addComponent(TFNombreDieta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FondoDietas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTCliente))
                .addGap(18, 18, 18)
                .addGroup(FondoDietas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TXTFechaInicio)
                    .addComponent(DateChooserFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FondoDietas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TXTFechaInicial)
                    .addComponent(DateChooserFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FondoDietas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTPesoInicio)
                    .addComponent(TFPesoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FondoDietas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTPesoFinal)
                    .addComponent(TFPesoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(FondoDietas2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonEliminar)
                    .addComponent(ButtonEditar)
                    .addComponent(ButtonGuardar))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoDietas2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoDietas2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBuscar;
    private javax.swing.JButton ButtonEditar;
    private javax.swing.JButton ButtonEliminar;
    private javax.swing.JButton ButtonGuardar;
    private javax.swing.JComboBox<String> CBCliente;
    private javax.swing.JComboBox<String> CBSeleccionarDieta;
    private com.toedter.calendar.JDateChooser DateChooserFechaFinal;
    private com.toedter.calendar.JDateChooser DateChooserFechaInicio;
    private javax.swing.JDesktopPane FondoDietas2;
    private javax.swing.JTextField TFNombreDieta;
    private javax.swing.JTextField TFPesoFinal;
    private javax.swing.JTextField TFPesoInicial;
    private javax.swing.JLabel TXTCliente;
    private javax.swing.JLabel TXTFechaInicial;
    private javax.swing.JLabel TXTFechaInicio;
    private javax.swing.JLabel TXTND;
    private javax.swing.JLabel TXTPesoFinal;
    private javax.swing.JLabel TXTPesoInicio;
    private javax.swing.JLabel TXTSeleccionarDieta;
    private javax.swing.JLabel barritasAguanteBoca;
    // End of variables declaration//GEN-END:variables
}
