/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nutricorp.visuales;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import nutricorp.AccesoADatos.CConection;

/**
 *
 * @author gg
 */
public class FiltrarporPeso extends javax.swing.JInternalFrame {

    /**
     * Creates new form FiltrarporPeso
     */
    Connection connection;
    PreparedStatement ps;
    ResultSet rs;
    String sql = "";

    public FiltrarporPeso() {
        initComponents();
        llenarComboEasy();

    }

    private void llenartabla() {

        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Nombre Cliente");
        modelo.addColumn("Peso Buscado");
        modelo.addColumn("Peso Actual");
        modelo.addColumn("Fecha Final");
        jTable1.setModel(modelo);

        try {
            // Establecer la conexión antes de la preparación de la sentencia SQL
            connection = CConection.getConexion();

            if (jComboBox1.getSelectedItem().equals("Logrado")) {
                sql = "SELECT  paciente.Nombre,dieta.pesoFinal,paciente.pesoActual,dieta.FechaFinal FROM `paciente` JOIN dieta ON (paciente.IdPaciente = dieta.IdPaciente) WHERE paciente.pesoActual<=dieta.pesoFinal";
            } else {
                sql = "SELECT  paciente.Nombre,dieta.pesoFinal,paciente.pesoActual,dieta.FechaFinal FROM `paciente` JOIN dieta ON (paciente.IdPaciente = dieta.IdPaciente) WHERE paciente.pesoActual>dieta.pesoFinal";
            }
            connection = CConection.getConexion();
            ps = connection.prepareStatement(sql);
            rs = ps.executeQuery();

            Object[] objeto = new Object[4];
            while (rs.next()) {
                objeto[0] = rs.getString("Nombre");
                objeto[1] = rs.getInt("pesoFinal");
                objeto[2] = rs.getInt("pesoActual");
                objeto[3] = rs.getDate("FechaFinal");
                modelo.addRow(objeto);
            }
            jTable1.setModel(modelo);
        } catch (SQLException | NumberFormatException e) {
            System.out.println("Error al cargar los datos de las comidas : " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setClosable(true);
        setTitle("Peso Logrado o No Logrado\n");

        jDesktopPane1.setBackground(new java.awt.Color(5, 47, 46));

        jComboBox1.setBackground(new java.awt.Color(244, 243, 197));
        jComboBox1.setOpaque(false);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(244, 243, 197));
        jLabel1.setForeground(new java.awt.Color(244, 243, 197));
        jLabel1.setText("Finalizo con:");

        jTable1.setBackground(new java.awt.Color(5, 47, 46));
        jTable1.setForeground(new java.awt.Color(244, 243, 197));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setEnabled(false);
        jTable1.setGridColor(new java.awt.Color(244, 243, 197));
        jTable1.setOpaque(false);
        jScrollPane1.setViewportView(jTable1);

        jDesktopPane1.setLayer(jComboBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        llenartabla();
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void llenarComboEasy() {
        jComboBox1.addItem("Logrado");
        jComboBox1.addItem("No Logrado");
    }

}
